// Список доступных тегов для выбора в админ-панели
export const availableTags = [
  { name: "C#", path: "/assets/logos/csharp.svg" },
  { name: ".Net", path: "/assets/logos/dotnet.svg" },
  { name: ".NET Core", path: "/assets/logos/dotnetcore.svg" },
  { name: "Ef Core", path: "/assets/logos/efcore.png" },
  { name: "TailwindCSS", path: "/assets/logos/tailwindcss.svg" },
  { name: "Auth0", path: "/assets/logos/auth0.svg" },
  { name: "React", path: "/assets/logos/react.svg" },
  { name: "SQLite", path: "/assets/logos/sqlite.svg" },
  { name: "Blazor", path: "/assets/logos/blazor.svg" },
  { name: "C++", path: "/assets/logos/cplusplus.svg" },
  { name: "Git", path: "/assets/logos/git.svg" },
  { name: "Microsoft", path: "/assets/logos/microsoft.svg" },
  { name: "WordPress", path: "/assets/logos/wordpress.svg" },
  { name: "HTML5", path: "/assets/logos/html5.svg" },
  { name: "CSS3", path: "/assets/logos/css3.svg" },
  { name: "Vite.js", path: "/assets/logos/vitejs.svg" },
  { name: "Azure", path: "/assets/logos/azure.svg" },
  { name: "Stripe", path: "/assets/logos/stripe.svg" },
  { name: "JavaScript", path: "/assets/logos/javascript.svg" },
  { name: "TypeScript", path: "/assets/logos/typescript.svg" },
  { name: "Node.js", path: "/assets/logos/nodejs.svg" },
  { name: "Python", path: "/assets/logos/python.svg" },
  { name: "MongoDB", path: "/assets/logos/mongodb.svg" },
  { name: "PostgreSQL", path: "/assets/logos/postgresql.svg" },
  { name: "Docker", path: "/assets/logos/docker.svg" },
  { name: "Kubernetes", path: "/assets/logos/kubernetes.svg" },
  { name: "AWS", path: "/assets/logos/aws.svg" },
  { name: "Firebase", path: "/assets/logos/firebase.svg" },
  { name: "Next.js", path: "/assets/logos/nextjs.svg" },
  { name: "Vue.js", path: "/assets/logos/vuejs.svg" },
  { name: "Angular", path: "/assets/logos/angular.svg" },
  { name: "Express", path: "/assets/logos/express.svg" },
  { name: "GraphQL", path: "/assets/logos/graphql.svg" },
  { name: "Redux", path: "/assets/logos/redux.svg" },
  { name: "Sass", path: "/assets/logos/sass.svg" },
  { name: "Bootstrap", path: "/assets/logos/bootstrap.svg" },
  { name: "Material-UI", path: "/assets/logos/materialui.svg" },
  { name: "Figma", path: "/assets/logos/figma.svg" },
  { name: "Photoshop", path: "/assets/logos/photoshop.svg" },
  { name: "Illustrator", path: "/assets/logos/illustrator.svg" },
];
